spring.application.name=TFG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tfg
spring.datasource.username=root
spring.datasource.password=INUBbKLu8j
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialize=true
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG

springdoc.api-docs.path=/api-docs